name: last_kingdom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  retrofit: ^2.0.1
  retrofit_generator: ^2.0.1+1
  json_annotation: ^4.1.0
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  logger: ^1.1.0

  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

